version: '3.8'
services:
  backend:
    build: ./BackEnd/hookhub-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}  
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hookHub_network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}  
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}       
    ports:
      - "5050:80"  
    depends_on:
      - postgres
    networks:
      - hookHub_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  frontend:
    build: ./FrontEnd
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - hookHub_network
  
networks:
  hookHub_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  